#!/bin/bash

CONFIG="$HOME/.config/dez_scripts/wofi/config.ini"
STYLE="$HOME/.config/dez_scripts/wofi/style.css"
COLORS="$HOME/.config/dez_scripts/wofi/colors"

if [[ ! $(pidof wofi) ]]; then
	wofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --color ${COLORS}
else
	pkill wofi
fi
