#!/usr/bin/env bash

# Check if albert is running using pgrep
if pgrep -x "albert" > /dev/null; then
    # If albert is running, just show it
    albert show
else
    # If albert is not running, start it and show it
    albert & # Start albert in background
    sleep 0.5 # Give it a moment to start
    albert show
fi
