

fileinfo:
    whitelist: [/mnt/Secondary/Documents/Media/TV_Shows, /mnt/Secondary/Documents/Media, /home/dez/Documents/Media]

players:
    monitored: [mpv]

general:
    enable_notifs:
        scrobble: no
version: '1.0'
